// Visual template presets configurations
// tpl-1 to tpl-60: FREE templates (existing)
// tpl-61 to tpl-120: PREMIUM templates (new dark/bold/magazine/creative layouts)
export const templatePresets = [
  // ============================================================
  // FREE TEMPLATES (tpl-1 to tpl-60) — Available to all users
  // ============================================================
  { id: 'tpl-1', name: 'Emerald Executive', category: 'Executive', layout: 'split-left', theme: 'emerald', font: 'modern', header: 'banner', desc: 'Emerald sidebar layout with bold banner header', isPremium: false },
  { id: 'tpl-2', name: 'Slate Executive', category: 'Executive', layout: 'split-left', theme: 'slate', font: 'modern', header: 'border', desc: 'Grey theme sidebar layout with bottom border outlines', isPremium: false },
  { id: 'tpl-3', name: 'Sapphire Split', category: 'Classic', layout: 'split-left', theme: 'navy', font: 'modern', header: 'clean', desc: 'Sleek navy sidebar layout with clean titles', isPremium: false },
  { id: 'tpl-4', name: 'Ruby Timeline', category: 'Creative', layout: 'timeline', theme: 'amber', font: 'modern', header: 'clean', desc: 'Timeline layout with crimson accents', isPremium: false },
  { id: 'tpl-5', name: 'Sunset Tech', category: 'Tech', layout: 'split-right', theme: 'amber', font: 'mono', header: 'clean', desc: 'Monospace tech template with right sidebar', isPremium: false },
  { id: 'tpl-6', name: 'Royal Creative', category: 'Creative', layout: 'classic', theme: 'purple', font: 'modern', header: 'banner', desc: 'Creative purple layout with bold banner header', isPremium: false },
  { id: 'tpl-7', name: 'Monochrome Minimal', category: 'Minimal', layout: 'timeline', theme: 'slate', font: 'modern', header: 'clean', desc: 'Clean, minimal single-column timeline', isPremium: false },
  { id: 'tpl-8', name: 'Mint Academic', category: 'Academic', layout: 'classic', theme: 'emerald', font: 'serif', header: 'border', desc: 'Academic layout with serif fonts and emerald borders', isPremium: false },
  { id: 'tpl-9', name: 'Indigo Corporate', category: 'Executive', layout: 'split-left', theme: 'navy', font: 'serif', header: 'banner', desc: 'Navy blue sidebar layout with classic serif headers', isPremium: false },
  { id: 'tpl-10', name: 'Tangerine Bold', category: 'Creative', layout: 'split-right', theme: 'amber', font: 'modern', header: 'banner', desc: 'Bold orange layout with banner header', isPremium: false },
  { id: 'tpl-11', name: 'Orchid Elegant', category: 'Creative', layout: 'classic', theme: 'purple', font: 'serif', header: 'border', desc: 'Orchid purple layout with elegant serif accents', isPremium: false },
  { id: 'tpl-12', name: 'Slate Compact', category: 'Minimal', layout: 'split-right', theme: 'slate', font: 'mono', header: 'clean', desc: 'Compact monospace layout for developers', isPremium: false },
  { id: 'tpl-13', name: 'Forest Engineer', category: 'Tech', layout: 'timeline', theme: 'emerald', font: 'mono', header: 'clean', desc: 'Mint timeline layout for developers and designers', isPremium: false },
  { id: 'tpl-14', name: 'Cobalt Scholar', category: 'Academic', layout: 'classic', theme: 'navy', font: 'serif', header: 'clean', desc: 'Sleek dark blue single-column academic style', isPremium: false },
  { id: 'tpl-15', name: 'Amber Executive', category: 'Executive', layout: 'split-left', theme: 'amber', font: 'modern', header: 'border', desc: 'Warm amber executive layout with vertical splits', isPremium: false },
  { id: 'tpl-16', name: 'Plum Creative', category: 'Creative', layout: 'split-right', theme: 'purple', font: 'modern', header: 'banner', desc: 'Deep violet creative layout with sidebar', isPremium: false },
  { id: 'tpl-17', name: 'Teal Professional', category: 'Classic', layout: 'split-left', theme: 'emerald', font: 'modern', header: 'border', desc: 'Professional teal left-sidebar template', isPremium: false },
  { id: 'tpl-18', name: 'Steel Tech', category: 'Tech', layout: 'classic', theme: 'slate', font: 'mono', header: 'banner', desc: 'Monospace tech template with steel-grey top banner', isPremium: false },
  { id: 'tpl-19', name: 'Navy Director', category: 'Executive', layout: 'classic', theme: 'navy', font: 'modern', header: 'border', desc: 'Bold corporate director layout with dark blue underlines', isPremium: false },
  { id: 'tpl-20', name: 'Violet Modernist', category: 'Creative', layout: 'timeline', theme: 'purple', font: 'modern', header: 'banner', desc: 'Purple timeline modernist layout with banner header', isPremium: false },
  { id: 'tpl-21', name: 'Coral Compact', category: 'Compact', layout: 'classic', theme: 'coral', font: 'modern', header: 'clean', desc: 'Compact layout with warm coral highlights', isPremium: false },
  { id: 'tpl-22', name: 'Olive Sage Minimalist', category: 'Minimal', layout: 'classic', theme: 'olive', font: 'serif', header: 'clean', desc: 'Earthy sage olive theme with minimalist lowercase headers', isPremium: false },
  { id: 'tpl-23', name: 'Rose Gold Creative', category: 'Creative', layout: 'classic', theme: 'rose', font: 'modern', header: 'border', desc: 'Creative rose theme with solid banner block headings', isPremium: false },
  { id: 'tpl-24', name: 'Chocolate Academic', category: 'Academic', layout: 'classic', theme: 'chocolate', font: 'serif', header: 'border', desc: 'Bronze brown theme with classic centred academic CV styling', isPremium: false },
  { id: 'tpl-25', name: 'Teal Split Modern', category: 'Classic', layout: 'split-left', theme: 'teal', font: 'modern', header: 'clean', desc: 'Teal theme with split column and vertical separator border', isPremium: false },
  { id: 'tpl-26', name: 'Crimson Executive', category: 'Executive', layout: 'split-right', theme: 'crimson', font: 'modern', header: 'border', desc: 'Ruby red theme with double header columns', isPremium: false },
  { id: 'tpl-27', name: 'Charcoal Tech Minimal', category: 'Tech', layout: 'classic', theme: 'charcoal', font: 'mono', header: 'clean', desc: 'Ultra clean dark grey theme, technical monospace layout', isPremium: false },
  { id: 'tpl-28', name: 'Indigo Hybrid', category: 'Creative', layout: 'split-left', theme: 'indigo', font: 'modern', header: 'banner', desc: 'Deep indigo theme with light card-styled sections', isPremium: false },
  { id: 'tpl-29', name: 'Gold Vintage Director', category: 'Executive', layout: 'classic', theme: 'gold', font: 'serif', header: 'border', desc: 'Mustard gold theme with elegant double borders', isPremium: false },
  { id: 'tpl-30', name: 'Mint Modernist', category: 'Creative', layout: 'timeline', theme: 'mint', font: 'modern', header: 'clean', desc: 'Soft mint green theme with square dashed timeline nodes', isPremium: false },
  { id: 'tpl-31', name: 'Lavender Elegant', category: 'Creative', layout: 'classic', theme: 'lavender', font: 'serif', header: 'clean', desc: 'Lavender theme with a decorative summary block', isPremium: false },
  { id: 'tpl-32', name: 'Sky Blue Academic', category: 'Academic', layout: 'classic', theme: 'sky', font: 'serif', header: 'border', desc: 'Sky blue theme with minimal academic layouts', isPremium: false },
  { id: 'tpl-33', name: 'Coral Creative Split', category: 'Creative', layout: 'split-left', theme: 'coral', font: 'modern', header: 'banner', desc: 'Coral theme with full-height left-sidebar', isPremium: false },
  { id: 'tpl-34', name: 'Olive Tech Grid', category: 'Tech', layout: 'split-right', theme: 'olive', font: 'mono', header: 'clean', desc: 'Sage theme with block skill capsules', isPremium: false },
  { id: 'tpl-35', name: 'Rose Executive', category: 'Executive', layout: 'classic', theme: 'rose', font: 'modern', header: 'banner', desc: 'Rose pink theme with banner header and center profile photo', isPremium: false },
  { id: 'tpl-36', name: 'Bronze Academic', category: 'Academic', layout: 'classic', theme: 'chocolate', font: 'serif', header: 'clean', desc: 'Warm bronze theme with elegant serif formatting', isPremium: false },
  { id: 'tpl-37', name: 'Teal Creative Timeline', category: 'Creative', layout: 'timeline', theme: 'teal', font: 'modern', header: 'clean', desc: 'Teal theme with diamond timeline nodes', isPremium: false },
  { id: 'tpl-38', name: 'Crimson Tech Split', category: 'Tech', layout: 'split-right', theme: 'crimson', font: 'mono', header: 'clean', desc: 'Deep red theme with right sidebar layout', isPremium: false },
  { id: 'tpl-39', name: 'Slate Compact Grid', category: 'Compact', layout: 'split-left', theme: 'slate', font: 'mono', header: 'clean', desc: 'Steel grey compact grid layout', isPremium: false },
  { id: 'tpl-40', name: 'Indigo Elegant Director', category: 'Executive', layout: 'classic', theme: 'indigo', font: 'serif', header: 'border', desc: 'Indigo theme with classic double underline header', isPremium: false },
  { id: 'tpl-41', name: 'Gold Bold Creative', category: 'Creative', layout: 'classic', theme: 'gold', font: 'modern', header: 'clean', desc: 'Gold theme with large bold display font', isPremium: false },
  { id: 'tpl-42', name: 'Mint Compact Minimal', category: 'Minimal', layout: 'classic', theme: 'mint', font: 'mono', header: 'clean', desc: 'Mint theme with tight vertical spacing', isPremium: false },
  { id: 'tpl-43', name: 'Lavender Split Scholar', category: 'Academic', layout: 'split-left', theme: 'lavender', font: 'serif', header: 'clean', desc: 'Lavender split scholar layout', isPremium: false },
  { id: 'tpl-44', name: 'Sky Academic Director', category: 'Academic', layout: 'classic', theme: 'sky', font: 'serif', header: 'border', desc: 'Sky blue elegant scholar layout', isPremium: false },
  { id: 'tpl-45', name: 'Coral Tech Minimalist', category: 'Minimal', layout: 'classic', theme: 'coral', font: 'mono', header: 'clean', desc: 'Coral theme with sleek left border', isPremium: false },
  { id: 'tpl-46', name: 'Olive Bold Executive', category: 'Executive', layout: 'classic', theme: 'olive', font: 'modern', header: 'banner', desc: 'Sage green bold corporate executive', isPremium: false },
  { id: 'tpl-47', name: 'Rose Elegant Split', category: 'Creative', layout: 'split-left', theme: 'rose', font: 'serif', header: 'clean', desc: 'Rose theme with split columns and rounded card backgrounds', isPremium: false },
  { id: 'tpl-48', name: 'Bronze Creative Scholar', category: 'Creative', layout: 'timeline', theme: 'chocolate', font: 'serif', header: 'clean', desc: 'Bronze timeline scholar layout', isPremium: false },
  { id: 'tpl-49', name: 'Teal Executive Grid', category: 'Executive', layout: 'split-left', theme: 'teal', font: 'modern', header: 'border', desc: 'Teal theme with split column layout', isPremium: false },
  { id: 'tpl-50', name: 'Crimson Elegant Compact', category: 'Compact', layout: 'classic', theme: 'crimson', font: 'serif', header: 'border', desc: 'Crimson compact margins elegant layout', isPremium: false },
  { id: 'tpl-51', name: 'Slate Technical Hybrid', category: 'Tech', layout: 'classic', theme: 'slate', font: 'mono', header: 'clean', desc: 'Slate technical hybrid layout', isPremium: false },
  { id: 'tpl-52', name: 'Indigo Compact Scholar', category: 'Academic', layout: 'classic', theme: 'indigo', font: 'serif', header: 'clean', desc: 'Indigo compact scholar single column', isPremium: false },
  { id: 'tpl-53', name: 'Gold Compact Minimal', category: 'Minimal', layout: 'classic', theme: 'gold', font: 'modern', header: 'clean', desc: 'Gold compact minimal layout', isPremium: false },
  { id: 'tpl-54', name: 'Mint Creative Executive', category: 'Executive', layout: 'split-left', theme: 'mint', font: 'modern', header: 'banner', desc: 'Mint theme with creative executive header banner', isPremium: false },
  { id: 'tpl-55', name: 'Lavender Tech Timeline', category: 'Tech', layout: 'timeline', theme: 'lavender', font: 'mono', header: 'clean', desc: 'Lavender tech timeline with solid track', isPremium: false },
  { id: 'tpl-56', name: 'Sky Compact Grid', category: 'Compact', layout: 'split-right', theme: 'sky', font: 'modern', header: 'clean', desc: 'Sky blue compact grid layout', isPremium: false },
  { id: 'tpl-57', name: 'Coral Academic Scholar', category: 'Academic', layout: 'classic', theme: 'coral', font: 'serif', header: 'border', desc: 'Coral academic scholar layout', isPremium: false },
  { id: 'tpl-58', name: 'Olive Creative Timeline', category: 'Creative', layout: 'timeline', theme: 'olive', font: 'serif', header: 'clean', desc: 'Sage timeline layout with elegant headers', isPremium: false },
  { id: 'tpl-59', name: 'Rose Technical Minimal', category: 'Minimal', layout: 'classic', theme: 'rose', font: 'mono', header: 'clean', desc: 'Rose technical layout with clean sidebar lines', isPremium: false },
  { id: 'tpl-60', name: 'Bronze Executive Compact', category: 'Executive', layout: 'split-right', theme: 'chocolate', font: 'modern', header: 'border', desc: 'Bronze executive compact split layout', isPremium: false },

  // ============================================================
  // PREMIUM TEMPLATES (tpl-61 to tpl-120) — Requires Premium
  // ============================================================

  // --- DARK-LEFT LAYOUT: Dark full-height left sidebar with white text ---
  { id: 'tpl-61', name: 'Obsidian Executive', category: 'Executive', layout: 'dark-left', theme: 'onyx', font: 'modern', header: 'clean', desc: 'Ultra-dark sidebar with crisp white text and modern typography', isPremium: false },
  { id: 'tpl-62', name: 'Midnight Director', category: 'Executive', layout: 'dark-left', theme: 'midnight', font: 'serif', header: 'clean', desc: 'Deep navy sidebar with elegant serif headings', isPremium: false },
  { id: 'tpl-63', name: 'Plum Prestige', category: 'Creative', layout: 'dark-left', theme: 'plum', font: 'modern', header: 'clean', desc: 'Rich purple sidebar with modern creative styling', isPremium: false },
  { id: 'tpl-64', name: 'Ocean Corporate', category: 'Executive', layout: 'dark-left', theme: 'ocean', font: 'modern', header: 'border', desc: 'Deep ocean blue sidebar with corporate accent borders', isPremium: false },
  { id: 'tpl-65', name: 'Graphite Architect', category: 'Tech', layout: 'dark-left', theme: 'graphite', font: 'mono', header: 'clean', desc: 'Dark charcoal sidebar with monospace developer styling', isPremium: false },
  { id: 'tpl-66', name: 'Wine Consultant', category: 'Executive', layout: 'dark-left', theme: 'wine', font: 'serif', header: 'border', desc: 'Burgundy sidebar with elegant serif consultant style', isPremium: false },
  { id: 'tpl-67', name: 'Forest Analyst', category: 'Classic', layout: 'dark-left', theme: 'forest', font: 'modern', header: 'clean', desc: 'Deep forest green sidebar with clean analytics look', isPremium: false },
  { id: 'tpl-68', name: 'Steel Engineer', category: 'Tech', layout: 'dark-left', theme: 'steel', font: 'mono', header: 'clean', desc: 'Steel blue sidebar with engineering monospace layout', isPremium: false },
  { id: 'tpl-69', name: 'Onyx Minimal', category: 'Minimal', layout: 'dark-left', theme: 'onyx', font: 'modern', header: 'clean', desc: 'Ultra-minimal black sidebar with white accents', isPremium: false },
  { id: 'tpl-70', name: 'Midnight Scholar', category: 'Academic', layout: 'dark-left', theme: 'midnight', font: 'serif', header: 'border', desc: 'Navy sidebar with academic serif styling', isPremium: false },
  { id: 'tpl-71', name: 'Plum Designer', category: 'Creative', layout: 'dark-left', theme: 'plum', font: 'modern', header: 'banner', desc: 'Purple sidebar with creative banner header', isPremium: false },
  { id: 'tpl-72', name: 'Ocean Strategist', category: 'Executive', layout: 'dark-left', theme: 'ocean', font: 'serif', header: 'clean', desc: 'Deep blue sidebar with strategic serif elegance', isPremium: false },
  { id: 'tpl-73', name: 'Graphite Coder', category: 'Tech', layout: 'dark-left', theme: 'graphite', font: 'mono', header: 'border', desc: 'Dark grey sidebar with code-styled monospace sections', isPremium: false },
  { id: 'tpl-74', name: 'Wine Academic', category: 'Academic', layout: 'dark-left', theme: 'wine', font: 'serif', header: 'clean', desc: 'Burgundy sidebar with scholarly serif layout', isPremium: false },
  { id: 'tpl-75', name: 'Forest Creative', category: 'Creative', layout: 'dark-left', theme: 'forest', font: 'modern', header: 'banner', desc: 'Forest green sidebar with creative banner', isPremium: false },

  // --- DARK-RIGHT LAYOUT: Dark full-height right sidebar ---
  { id: 'tpl-76', name: 'Onyx Inverse', category: 'Creative', layout: 'dark-right', theme: 'onyx', font: 'modern', header: 'clean', desc: 'Inverted dark sidebar on right with main content left', isPremium: false },
  { id: 'tpl-77', name: 'Midnight Reverse', category: 'Executive', layout: 'dark-right', theme: 'midnight', font: 'modern', header: 'border', desc: 'Navy right sidebar with executive borders', isPremium: false },
  { id: 'tpl-78', name: 'Plum Flip', category: 'Creative', layout: 'dark-right', theme: 'plum', font: 'serif', header: 'clean', desc: 'Purple right sidebar with serif creative styling', isPremium: false },
  { id: 'tpl-79', name: 'Ocean Reverse Elite', category: 'Executive', layout: 'dark-right', theme: 'ocean', font: 'modern', header: 'clean', desc: 'Deep blue right sidebar with elite corporate look', isPremium: false },
  { id: 'tpl-80', name: 'Graphite Reverse Tech', category: 'Tech', layout: 'dark-right', theme: 'graphite', font: 'mono', header: 'clean', desc: 'Dark right sidebar with tech monospace layout', isPremium: false },
  { id: 'tpl-81', name: 'Wine Reverse Elegant', category: 'Executive', layout: 'dark-right', theme: 'wine', font: 'serif', header: 'border', desc: 'Burgundy right sidebar with elegant serif accents', isPremium: false },
  { id: 'tpl-82', name: 'Forest Reverse Pro', category: 'Classic', layout: 'dark-right', theme: 'forest', font: 'modern', header: 'clean', desc: 'Forest green right sidebar with professional look', isPremium: false },
  { id: 'tpl-83', name: 'Steel Reverse Builder', category: 'Tech', layout: 'dark-right', theme: 'steel', font: 'mono', header: 'border', desc: 'Steel blue right sidebar with builder monospace style', isPremium: false },
  { id: 'tpl-84', name: 'Onyx Reverse Minimal', category: 'Minimal', layout: 'dark-right', theme: 'onyx', font: 'modern', header: 'clean', desc: 'Ultra-clean black right sidebar minimal layout', isPremium: false },
  { id: 'tpl-85', name: 'Midnight Reverse Scholar', category: 'Academic', layout: 'dark-right', theme: 'midnight', font: 'serif', header: 'clean', desc: 'Navy right sidebar with academic serif styling', isPremium: false },

  // --- BOLD-HEADER LAYOUT: Full-width colored header bar, two-column body ---
  { id: 'tpl-86', name: 'Onyx Crown', category: 'Executive', layout: 'bold-header', theme: 'onyx', font: 'modern', header: 'banner', desc: 'Full-width black header bar with bold name display', isPremium: false },
  { id: 'tpl-87', name: 'Midnight Monarch', category: 'Executive', layout: 'bold-header', theme: 'midnight', font: 'serif', header: 'banner', desc: 'Navy blue full-width header with regal serif fonts', isPremium: false },
  { id: 'tpl-88', name: 'Plum Spectrum', category: 'Creative', layout: 'bold-header', theme: 'plum', font: 'modern', header: 'banner', desc: 'Purple full-width header with creative spectrum styling', isPremium: false },
  { id: 'tpl-89', name: 'Ocean Horizon', category: 'Executive', layout: 'bold-header', theme: 'ocean', font: 'modern', header: 'banner', desc: 'Deep blue full-width header with horizon line accents', isPremium: false },
  { id: 'tpl-90', name: 'Graphite Terminal', category: 'Tech', layout: 'bold-header', theme: 'graphite', font: 'mono', header: 'banner', desc: 'Dark grey full-width header with terminal monospace style', isPremium: false },
  { id: 'tpl-91', name: 'Wine Heritage', category: 'Executive', layout: 'bold-header', theme: 'wine', font: 'serif', header: 'banner', desc: 'Burgundy full-width header with heritage serif elegance', isPremium: false },
  { id: 'tpl-92', name: 'Forest Canopy', category: 'Creative', layout: 'bold-header', theme: 'forest', font: 'modern', header: 'banner', desc: 'Forest green full-width header with nature-inspired design', isPremium: false },
  { id: 'tpl-93', name: 'Steel Forge', category: 'Tech', layout: 'bold-header', theme: 'steel', font: 'mono', header: 'banner', desc: 'Steel blue full-width header with forge-style tech layout', isPremium: false },
  { id: 'tpl-94', name: 'Onyx Statement', category: 'Creative', layout: 'bold-header', theme: 'onyx', font: 'serif', header: 'banner', desc: 'Black full-width header with serif statement typography', isPremium: false },
  { id: 'tpl-95', name: 'Midnight Pinnacle', category: 'Executive', layout: 'bold-header', theme: 'midnight', font: 'modern', header: 'banner', desc: 'Navy full-width header with pinnacle modern styling', isPremium: false },
  { id: 'tpl-96', name: 'Plum Artisan', category: 'Creative', layout: 'bold-header', theme: 'plum', font: 'serif', header: 'banner', desc: 'Purple full-width header with artisan serif craft', isPremium: false },
  { id: 'tpl-97', name: 'Ocean Depths', category: 'Classic', layout: 'bold-header', theme: 'ocean', font: 'serif', header: 'banner', desc: 'Deep ocean full-width header with classic depths styling', isPremium: false },
  { id: 'tpl-98', name: 'Graphite Industrial', category: 'Tech', layout: 'bold-header', theme: 'graphite', font: 'modern', header: 'banner', desc: 'Charcoal industrial header with modern tech sections', isPremium: false },
  { id: 'tpl-99', name: 'Wine Regal', category: 'Executive', layout: 'bold-header', theme: 'wine', font: 'modern', header: 'banner', desc: 'Burgundy regal header with modern executive layout', isPremium: false },
  { id: 'tpl-100', name: 'Steel Precision', category: 'Tech', layout: 'bold-header', theme: 'steel', font: 'mono', header: 'banner', desc: 'Steel precision header with monospace tech sections', isPremium: false },

  // --- MAGAZINE LAYOUT: Creative/artistic with accent borders, large photo area ---
  { id: 'tpl-101', name: 'Onyx Vogue', category: 'Creative', layout: 'magazine', theme: 'onyx', font: 'modern', header: 'clean', desc: 'Magazine-style with bold borders and editorial layout', isPremium: false },
  { id: 'tpl-102', name: 'Midnight Portfolio', category: 'Creative', layout: 'magazine', theme: 'midnight', font: 'modern', header: 'clean', desc: 'Navy magazine portfolio with creative editorial sections', isPremium: false },
  { id: 'tpl-103', name: 'Plum Editorial', category: 'Creative', layout: 'magazine', theme: 'plum', font: 'serif', header: 'clean', desc: 'Purple magazine editorial with serif typography', isPremium: false },
  { id: 'tpl-104', name: 'Ocean Curator', category: 'Creative', layout: 'magazine', theme: 'ocean', font: 'modern', header: 'border', desc: 'Deep blue magazine with curated section borders', isPremium: false },
  { id: 'tpl-105', name: 'Graphite Studio', category: 'Creative', layout: 'magazine', theme: 'graphite', font: 'modern', header: 'clean', desc: 'Dark studio magazine layout with creative photo area', isPremium: false },
  { id: 'tpl-106', name: 'Wine Gallery', category: 'Creative', layout: 'magazine', theme: 'wine', font: 'serif', header: 'clean', desc: 'Burgundy gallery magazine with serif editorial styling', isPremium: false },
  { id: 'tpl-107', name: 'Forest Journal', category: 'Creative', layout: 'magazine', theme: 'forest', font: 'serif', header: 'border', desc: 'Forest green journal magazine with academic serif look', isPremium: false },
  { id: 'tpl-108', name: 'Steel Chronicle', category: 'Tech', layout: 'magazine', theme: 'steel', font: 'mono', header: 'clean', desc: 'Steel blue chronicle magazine with tech monospace style', isPremium: false },
  { id: 'tpl-109', name: 'Onyx Showcase', category: 'Creative', layout: 'magazine', theme: 'onyx', font: 'serif', header: 'border', desc: 'Black showcase magazine with serif borders', isPremium: false },
  { id: 'tpl-110', name: 'Midnight Gazette', category: 'Classic', layout: 'magazine', theme: 'midnight', font: 'serif', header: 'border', desc: 'Navy gazette magazine with classic serif editorial', isPremium: false },

  // --- MIXED PREMIUM: Various dark themes with existing layouts ---
  { id: 'tpl-111', name: 'Onyx Timeline', category: 'Creative', layout: 'timeline', theme: 'onyx', font: 'modern', header: 'clean', desc: 'Ultra-dark timeline with white accent nodes', isPremium: false },
  { id: 'tpl-112', name: 'Midnight Classic', category: 'Classic', layout: 'classic', theme: 'midnight', font: 'modern', header: 'border', desc: 'Navy single-column classic with midnight blue accents', isPremium: false },
  { id: 'tpl-113', name: 'Plum Timeline', category: 'Creative', layout: 'timeline', theme: 'plum', font: 'modern', header: 'clean', desc: 'Purple timeline with plum accent nodes', isPremium: false },
  { id: 'tpl-114', name: 'Ocean Classic', category: 'Classic', layout: 'classic', theme: 'ocean', font: 'serif', header: 'border', desc: 'Deep ocean single-column classic with serif elegance', isPremium: false },
  { id: 'tpl-115', name: 'Graphite Classic', category: 'Minimal', layout: 'classic', theme: 'graphite', font: 'mono', header: 'clean', desc: 'Charcoal single-column minimal with monospace', isPremium: false },
  { id: 'tpl-116', name: 'Wine Split Elite', category: 'Executive', layout: 'split-left', theme: 'wine', font: 'serif', header: 'border', desc: 'Burgundy split layout with elite serif styling', isPremium: false },
  { id: 'tpl-117', name: 'Forest Split Natural', category: 'Classic', layout: 'split-left', theme: 'forest', font: 'modern', header: 'clean', desc: 'Forest green split layout with natural modern look', isPremium: false },
  { id: 'tpl-118', name: 'Steel Timeline', category: 'Tech', layout: 'timeline', theme: 'steel', font: 'mono', header: 'clean', desc: 'Steel blue timeline with tech monospace nodes', isPremium: false },
  { id: 'tpl-119', name: 'Midnight Split Elite', category: 'Executive', layout: 'split-right', theme: 'midnight', font: 'modern', header: 'border', desc: 'Navy right-split layout with executive borders', isPremium: false },
  { id: 'tpl-120', name: 'Onyx Bold Statement', category: 'Creative', layout: 'classic', theme: 'onyx', font: 'modern', header: 'banner', desc: 'Ultra-dark classic layout with bold banner statement', isPremium: false },

  // --- NEW CUSTOM REFERENCE LAYOUTS (tpl-121 to tpl-160) ---
  { id: 'tpl-121', name: 'Sienna Rounded', category: 'Creative', layout: 'rounded-cards', theme: 'chocolate', font: 'serif', header: 'clean', desc: 'Beige layout with floating rounded white card sections and bronze accents', isPremium: false },
  { id: 'tpl-122', name: 'Verdant Rounded', category: 'Classic', layout: 'rounded-cards', theme: 'emerald', font: 'modern', header: 'border', desc: 'Floating rounded white cards on beige background with soft green headings', isPremium: false },
  { id: 'tpl-123', name: 'Sapphire Rounded', category: 'Executive', layout: 'rounded-cards', theme: 'navy', font: 'modern', header: 'clean', desc: 'Elegant navy theme rounded card blocks on sandy beige background', isPremium: false },
  { id: 'tpl-124', name: 'Slate Rounded', category: 'Minimal', layout: 'rounded-cards', theme: 'slate', font: 'mono', header: 'clean', desc: 'Minimalist grey card layout with clean sans-serif typography', isPremium: false },
  { id: 'tpl-125', name: 'Ruby Rounded', category: 'Creative', layout: 'rounded-cards', theme: 'crimson', font: 'serif', header: 'border', desc: 'Creative red accents rounded sections layout with serif title', isPremium: false },
  { id: 'tpl-126', name: 'Amber Rounded', category: 'Tech', layout: 'rounded-cards', theme: 'amber', font: 'modern', header: 'clean', desc: 'Warm amber rounded card layout for modern developers', isPremium: false },
  { id: 'tpl-127', name: 'Terra Organic', category: 'Creative', layout: 'organic-curves', theme: 'chocolate', font: 'serif', header: 'clean', desc: 'curvy warm-sand block layout with bronze accents and chic margins', isPremium: false },
  { id: 'tpl-128', name: 'Olive Organic', category: 'Classic', layout: 'organic-curves', theme: 'olive', font: 'modern', header: 'border', desc: 'Curved custom frames on sage green background with modern dividers', isPremium: false },
  { id: 'tpl-129', name: 'Indigo Organic', category: 'Executive', layout: 'organic-curves', theme: 'indigo', font: 'modern', header: 'clean', desc: 'Chic indigo organic curved borders with corporate font details', isPremium: false },
  { id: 'tpl-130', name: 'Amethyst Organic', category: 'Creative', layout: 'organic-curves', theme: 'purple', font: 'modern', header: 'banner', desc: 'Bright purple organic curves layout with bold header banner', isPremium: false },
  { id: 'tpl-131', name: 'Mint Organic', category: 'Minimal', layout: 'organic-curves', theme: 'mint', font: 'mono', header: 'clean', desc: 'Minimal monospace layout with sage green curvy shapes', isPremium: false },
  { id: 'tpl-132', name: 'Bronze Organic', category: 'Academic', layout: 'organic-curves', theme: 'chocolate', font: 'serif', header: 'clean', desc: 'Academic layout with earthy bronze curvy details and serif texts', isPremium: false },
  { id: 'tpl-133', name: 'Vanguard Green', category: 'Tech', layout: 'flat-accent', theme: 'emerald', font: 'modern', header: 'clean', desc: 'High-contrast geometric layout with bold green dividers', isPremium: false },
  { id: 'tpl-134', name: 'Corporate Blue', category: 'Executive', layout: 'flat-accent', theme: 'navy', font: 'modern', header: 'border', desc: 'Clean corporate split layout with deep navy solid margins', isPremium: false },
  { id: 'tpl-135', name: 'Apex Teal', category: 'Tech', layout: 'flat-accent', theme: 'teal', font: 'mono', header: 'clean', desc: 'Technical split layout with teal geometric accents and flat styles', isPremium: false },
  { id: 'tpl-136', name: 'Crimson Flat', category: 'Creative', layout: 'flat-accent', theme: 'crimson', font: 'modern', header: 'border', desc: 'Vibrant crimson split layout with solid geometric block styling', isPremium: false },
  { id: 'tpl-137', name: 'Amber Flat', category: 'Classic', layout: 'flat-accent', theme: 'amber', font: 'serif', header: 'clean', desc: 'Classic layout with amber accent rules and clean serif headers', isPremium: false },
  { id: 'tpl-138', name: 'Onyx Flat', category: 'Minimal', layout: 'flat-accent', theme: 'onyx', font: 'modern', header: 'clean', desc: 'Obsidian dark flat accent layout with bold borders and margins', isPremium: false },
  { id: 'tpl-139', name: 'Wine Wave', category: 'Executive', layout: 'wave-header', theme: 'wine', font: 'serif', header: 'banner', desc: 'Deep wine curved wave top banner layout with star bullets', isPremium: false },
  { id: 'tpl-140', name: 'Ocean Wave', category: 'Classic', layout: 'wave-header', theme: 'navy', font: 'modern', header: 'clean', desc: 'Deep navy wave-banner header with structured body columns', isPremium: false },
  { id: 'tpl-141', name: 'Forest Wave', category: 'Creative', layout: 'wave-header', theme: 'forest', font: 'modern', header: 'banner', desc: 'Creative forest green curved top banner with decorative stars', isPremium: false },
  { id: 'tpl-142', name: 'Plum Wave', category: 'Creative', layout: 'wave-header', theme: 'plum', font: 'serif', header: 'border', desc: 'Deep purple wave header layout with elegant serif accents', isPremium: false },
  { id: 'tpl-143', name: 'Graphite Wave', category: 'Minimal', layout: 'wave-header', theme: 'slate', font: 'mono', header: 'clean', desc: 'Slate grey wave banner header with clean monospace fonts', isPremium: false },
  { id: 'tpl-144', name: 'Steel Wave', category: 'Tech', layout: 'wave-header', theme: 'steel', font: 'mono', header: 'clean', desc: 'Steel blue curved top header layout with technical info grids', isPremium: false },
  { id: 'tpl-145', name: 'Teal Rounded', category: 'Compact', layout: 'rounded-cards', theme: 'teal', font: 'modern', header: 'clean', desc: 'Compact layout with floating white cards and teal highlight rules', isPremium: false },
  { id: 'tpl-146', name: 'Rose Rounded', category: 'Creative', layout: 'rounded-cards', theme: 'rose', font: 'serif', header: 'border', desc: 'Elegant rose pink rounded white card blocks on beige background', isPremium: false },
  { id: 'tpl-147', name: 'Charcoal Rounded', category: 'Tech', layout: 'rounded-cards', theme: 'charcoal', font: 'mono', header: 'clean', desc: 'Monospace tech cards layout on modern grey background', isPremium: false },
  { id: 'tpl-148', name: 'Lavender Organic', category: 'Creative', layout: 'organic-curves', theme: 'lavender', font: 'serif', header: 'clean', desc: 'Curved organic layout with soft lavender borders and serif title', isPremium: false },
  { id: 'tpl-149', name: 'Sky Organic', category: 'Classic', layout: 'organic-curves', theme: 'sky', font: 'modern', header: 'border', desc: 'Soft sky blue organic curvy containers with modern highlights', isPremium: false },
  { id: 'tpl-150', name: 'Coral Organic', category: 'Compact', layout: 'organic-curves', theme: 'coral', font: 'modern', header: 'clean', desc: 'Compact organic layout with coral orange curves and accents', isPremium: false },
  { id: 'tpl-151', name: 'Gold Flat', category: 'Executive', layout: 'flat-accent', theme: 'gold', font: 'serif', header: 'border', desc: 'Gold yellow bold corporate split layout with serif title', isPremium: false },
  { id: 'tpl-152', name: 'Lavender Flat', category: 'Creative', layout: 'flat-accent', theme: 'lavender', font: 'modern', header: 'clean', desc: 'Modern layout with solid purple accents and geometric borders', isPremium: false },
  { id: 'tpl-153', name: 'Sky Flat', category: 'Academic', layout: 'flat-accent', theme: 'sky', font: 'serif', header: 'border', desc: 'Academic layout with clear sky blue accent lines and serif detail', isPremium: false },
  { id: 'tpl-154', name: 'Rose Flat', category: 'Compact', layout: 'flat-accent', theme: 'rose', font: 'modern', header: 'clean', desc: 'Compact geometric flat layout with rose accents', isPremium: false },
  { id: 'tpl-155', name: 'Gold Wave', category: 'Executive', layout: 'wave-header', theme: 'gold', font: 'serif', header: 'border', desc: 'Regal gold yellow curved wave header with serif subtitles', isPremium: false },
  { id: 'tpl-156', name: 'Coral Wave', category: 'Creative', layout: 'wave-header', theme: 'coral', font: 'modern', header: 'banner', desc: 'Vibrant coral wave top banner with custom star-bullet lists', isPremium: false },
  { id: 'tpl-157', name: 'Lavender Wave', category: 'Academic', layout: 'wave-header', theme: 'lavender', font: 'serif', header: 'clean', desc: 'Scholarly lavender wave header layout with classic serif text', isPremium: false },
  { id: 'tpl-158', name: 'Sky Wave', category: 'Compact', layout: 'wave-header', theme: 'sky', font: 'modern', header: 'clean', desc: 'Compact margins sky blue wave header layout', isPremium: false },
  { id: 'tpl-159', name: 'Sage Wave', category: 'Tech', layout: 'wave-header', theme: 'olive', font: 'mono', header: 'clean', desc: 'Sage olive tech wave layout with engineering monospace rules', isPremium: false },
  { id: 'tpl-160', name: 'Obsidian Wave', category: 'Minimal', layout: 'wave-header', theme: 'onyx', font: 'modern', header: 'clean', desc: 'Clean slate black curved wave header with minimalist font sizes', isPremium: false },

  // --- MINIMALIST & TECH-FOCUSED (tpl-161 to tpl-170) ---
  { id: 'tpl-161', name: 'The Core Stack', category: 'Tech', layout: 'flat-accent', theme: 'emerald', font: 'modern', header: 'clean', desc: 'Features a stark left border highlighting core languages and clean project details', isPremium: false },
  { id: 'tpl-162', name: 'The Git Log', category: 'Tech', layout: 'classic', theme: 'slate', font: 'mono', header: 'clean', desc: 'Designed to resemble a clean markdown file with monospaced headers and subtle gray lines', isPremium: false },
  { id: 'tpl-163', name: 'The Light Mode Stripe', category: 'Tech', layout: 'split-left', theme: 'sky', font: 'modern', header: 'clean', desc: 'Sleek off-white layout with a single royal blue accent color and high-contrast typography', isPremium: false },
  { id: 'tpl-164', name: 'The Modern Sandbox', category: 'Tech', layout: 'split-left', theme: 'charcoal', font: 'modern', header: 'border', desc: 'Employs a crisp grid layout with thin borders separating sections, mimicking a dashboard', isPremium: false },
  { id: 'tpl-165', name: 'The Dev Container', category: 'Tech', layout: 'bold-header', theme: 'onyx', font: 'mono', header: 'banner', desc: 'Dedicated dark-themed header snippet for contact details, paired with standard body layout', isPremium: false },
  { id: 'tpl-166', name: 'The API Ref', category: 'Tech', layout: 'split-right', theme: 'slate', font: 'mono', header: 'clean', desc: 'Structured like modern documentation platforms (e.g. Stripe docs) for dense tech information', isPremium: false },
  { id: 'tpl-167', name: 'The Micro-Spacing', category: 'Minimal', layout: 'classic', theme: 'charcoal', font: 'modern', header: 'clean', desc: 'Focuses on tight, precise margins and letter spacing for a dense, organized single-page sheet', isPremium: false },
  { id: 'tpl-168', name: 'The Fluid Grid', category: 'Tech', layout: 'split-left', theme: 'slate', font: 'modern', header: 'border', desc: 'Asymmetric grid layout assigning 35% of the page to technical skills and 65% to milestones', isPremium: false },
  { id: 'tpl-169', name: 'The Clean Node', category: 'Tech', layout: 'timeline', theme: 'emerald', font: 'modern', header: 'clean', desc: 'Subtle vertical timeline axis line running down the experience section to connect work history', isPremium: false },
  { id: 'tpl-170', name: 'The Pure System', category: 'Minimal', layout: 'classic', theme: 'charcoal', font: 'modern', header: 'clean', desc: 'Uses system default fonts with deep charcoal text on unblemished background for fast parsing', isPremium: false },

  // --- CREATIVE & DESIGN-CENTRIC (tpl-171 to tpl-180) ---
  { id: 'tpl-171', name: 'The Vector Path', category: 'Creative', layout: 'classic', theme: 'indigo', font: 'modern', header: 'clean', desc: 'Uses clean geometric frames and generous whitespace to emphasize visual layout balance', isPremium: false },
  { id: 'tpl-172', name: 'The Editorial Serif', category: 'Creative', layout: 'organic-curves', theme: 'chocolate', font: 'serif', header: 'clean', desc: 'Blends a high-end serif header font with clean sans-serif body text, editorial styling', isPremium: false },
  { id: 'tpl-173', name: 'The Duotone Edge', category: 'Creative', layout: 'dark-left', theme: 'graphite', font: 'modern', header: 'clean', desc: 'Two-column structure utilizing a deep slate background for the left column and white for the right', isPremium: false },
  { id: 'tpl-174', name: 'The Canvas Frame', category: 'Creative', layout: 'classic', theme: 'rose', font: 'modern', header: 'border', desc: 'Features an intentional outer border wrapper enclosing the resume, treating the page like art', isPremium: false },
  { id: 'tpl-175', name: 'The Modern Accent', category: 'Creative', layout: 'timeline', theme: 'coral', font: 'modern', header: 'clean', desc: 'Uses bright coral pop highlights exclusively for dates and section header icon indicators', isPremium: false },
  { id: 'tpl-176', name: 'The Block Palette', category: 'Creative', layout: 'rounded-cards', theme: 'lavender', font: 'modern', header: 'clean', desc: 'Divides content into pastel-tinted background modules, creating distinct visual card sections', isPremium: false },
  { id: 'tpl-177', name: 'The Gallery Brief', category: 'Creative', layout: 'split-left', theme: 'teal', font: 'modern', header: 'border', desc: 'Includes clean link badges and portfolio previews styled explicitly for design showcases', isPremium: false },
  { id: 'tpl-178', name: 'The Neo-Grotesque', category: 'Creative', layout: 'bold-header', theme: 'onyx', font: 'modern', header: 'banner', desc: 'Features heavy, bold headlines contrasted sharply with thin, high-readability body details', isPremium: false },
  { id: 'tpl-179', name: 'The Clean Line', category: 'Creative', layout: 'classic', theme: 'slate', font: 'modern', header: 'clean', desc: 'Replaces traditional bullet points with thin horizontal rules, giving your milestones a sleek feel', isPremium: false },
  { id: 'tpl-180', name: 'The Monogram Slate', category: 'Creative', layout: 'split-right', theme: 'slate', font: 'serif', header: 'clean', desc: 'Showcases an elegant monogram brand badge in the top sidebar column as a unique anchor', isPremium: false },

  // --- HIGH-END CORPORATE & EXECUTIVE (tpl-181 to tpl-190) ---
  { id: 'tpl-181', name: 'The Wall Street Standard', category: 'Executive', layout: 'classic', theme: 'navy', font: 'serif', header: 'border', desc: 'Traditional single-column layout focusing on elite typography hierarchy and zero clutter', isPremium: false },
  { id: 'tpl-182', name: 'The Ivy League', category: 'Executive', layout: 'classic', theme: 'gold', font: 'serif', header: 'border', desc: 'Features a centered, formal header layout with traditional font styling and classic prestige', isPremium: false },
  { id: 'tpl-183', name: 'The Double Column Executive', category: 'Executive', layout: 'split-left', theme: 'navy', font: 'modern', header: 'clean', desc: 'Divides page into two equal halves to balance rich text descriptions with analytical metrics', isPremium: false },
  { id: 'tpl-184', name: 'The Navy Elite', category: 'Executive', layout: 'classic', theme: 'midnight', font: 'modern', header: 'border', desc: 'Incorporates rich midnight-blue tones strictly for section headers to convey trust and authority', isPremium: false },
  { id: 'tpl-185', name: 'The Emerald Border', category: 'Executive', layout: 'flat-accent', theme: 'forest', font: 'serif', header: 'clean', desc: 'Uses deep forest green dividers to project stability and high-end management prestige', isPremium: false },
  { id: 'tpl-186', name: 'The Milestone Tracker', category: 'Executive', layout: 'timeline', theme: 'charcoal', font: 'modern', header: 'clean', desc: 'Places employment years prominently on the far left, creating an easy chronological scan', isPremium: false },
  { id: 'tpl-187', name: 'The Dense Professional', category: 'Executive', layout: 'classic', theme: 'slate', font: 'modern', header: 'clean', desc: 'Designed with slim vertical padding, allowing seasoned profiles to fit 10+ years onto one sheet', isPremium: false },
  { id: 'tpl-188', name: 'The Corporate Column', category: 'Executive', layout: 'split-left', theme: 'navy', font: 'modern', header: 'border', desc: 'Features a dedicated left sidebar highlighting board memberships, languages, and credentials', isPremium: false },
  { id: 'tpl-189', name: 'The Narrative Summary', category: 'Executive', layout: 'bold-header', theme: 'wine', font: 'serif', header: 'banner', desc: 'Allocates a full-width block at the top for an impactful, paragraph-style executive summary', isPremium: false },
  { id: 'tpl-190', name: 'The Classic Charcoal', category: 'Executive', layout: 'classic', theme: 'charcoal', font: 'modern', header: 'clean', desc: 'Replaces pitch-black text with an elegant off-black charcoal hue to reduce digital eye strain', isPremium: false },

  // --- ACADEMIC & RESEARCH (tpl-191 to tpl-200) ---
  { id: 'tpl-191', name: 'The CV Master', category: 'Academic', layout: 'classic', theme: 'navy', font: 'serif', header: 'border', desc: 'Academic layout built specifically for multi-page scaling to prevent page breaks clipping text', isPremium: false },
  { id: 'tpl-192', name: 'The Citations Standard', category: 'Academic', layout: 'classic', theme: 'slate', font: 'serif', header: 'clean', desc: 'Features specialized formatting blocks tailored for listing published papers and journal entries', isPremium: false },
  { id: 'tpl-193', name: 'The Grant Tracker', category: 'Academic', layout: 'split-left', theme: 'teal', font: 'serif', header: 'clean', desc: 'Highlights research funding, university grants, and academic awards in a distinct column', isPremium: false },
  { id: 'tpl-194', name: 'The Clean Index', category: 'Academic', layout: 'timeline', theme: 'charcoal', font: 'mono', header: 'clean', desc: 'Formatted like a scientific abstract or research index sheet for precise data presentations', isPremium: false },
  { id: 'tpl-195', name: 'The Lab Narrative', category: 'Academic', layout: 'split-left', theme: 'emerald', font: 'modern', header: 'border', desc: 'Dedications for lab proficiencies, chemical equipment, or software stack compliance profiles', isPremium: false },
  { id: 'tpl-196', name: 'The Chrono-Academic', category: 'Academic', layout: 'timeline', theme: 'chocolate', font: 'serif', header: 'clean', desc: 'Features an expanded timeline layout detailing teaching assistant history and student mentorships', isPremium: false },
  { id: 'tpl-197', name: 'The Thesis Accent', category: 'Academic', layout: 'bold-header', theme: 'navy', font: 'serif', header: 'banner', desc: 'Includes a prominent block immediately below the header to display the candidate\'s thesis', isPremium: false },
  { id: 'tpl-198', name: 'The Editorial Margin', category: 'Academic', layout: 'classic', theme: 'slate', font: 'serif', header: 'border', desc: 'Incorporates broad, classic 1-inch margins on all sides to prioritize formal reading comfort', isPremium: false },
  { id: 'tpl-199', name: 'The Project Grid', category: 'Academic', layout: 'split-left', theme: 'sky', font: 'modern', header: 'clean', desc: 'Organizes distinct engineering or scientific research projects into neat quadrants', isPremium: false },
  { id: 'tpl-200', name: 'The Plain Text Elite', category: 'Academic', layout: 'classic', theme: 'charcoal', font: 'modern', header: 'clean', desc: 'Strips away graphic components to maximize absolute parsing compatibility for job boards', isPremium: false },

  // --- STARTUP & HIGH-GROWTH (tpl-201 to tpl-210) ---
  { id: 'tpl-201', name: 'The Metric High', category: 'Creative', layout: 'bold-header', theme: 'amber', font: 'modern', header: 'banner', desc: 'Places emphasis on impact by featuring a bold metrics callout row highlighting achievements', isPremium: false },
  { id: 'tpl-202', name: 'The Modern Split', category: 'Classic', layout: 'split-left', theme: 'teal', font: 'modern', header: 'clean', desc: 'A 25/75 column split that lets short skill keywords sit perfectly alongside project detail', isPremium: false },
  { id: 'tpl-203', name: 'The Agile Layout', category: 'Tech', layout: 'timeline', theme: 'mint', font: 'mono', header: 'clean', desc: 'Styled with minimalist bullet icons and clean section spacing to echo project management', isPremium: false },
  { id: 'tpl-204', name: 'The Impact First', category: 'Creative', layout: 'classic', theme: 'coral', font: 'modern', header: 'border', desc: 'Boldly highlights the first 3 words of every bullet point to catch fast-scrolling recruiters', isPremium: false },
  { id: 'tpl-205', name: 'The Core Values Grid', category: 'Classic', layout: 'split-left', theme: 'sky', font: 'modern', header: 'clean', desc: 'Features a dedicated block highlighting the candidate\'s workplace and collaboration principles', isPremium: false },
  { id: 'tpl-206', name: 'The Tech Stack Ribbon', category: 'Tech', layout: 'bold-header', theme: 'steel', font: 'mono', header: 'banner', desc: 'Includes a row of sleek, minimal text badges near the header displaying key developer tools', isPremium: false },
  { id: 'tpl-207', name: 'The Hybrid Lead', category: 'Executive', layout: 'split-left', theme: 'emerald', font: 'modern', header: 'border', desc: 'Balances technical implementation descriptions with product growth and team leadership metrics', isPremium: false },
  { id: 'tpl-208', name: 'The Growth Timeline', category: 'Creative', layout: 'timeline', theme: 'amber', font: 'modern', header: 'clean', desc: 'Uses an open, modern vertical line timeline to emphasize rapid, year-over-year progression', isPremium: false },
  { id: 'tpl-209', name: 'The Scaled Minimalist', category: 'Minimal', layout: 'classic', theme: 'slate', font: 'mono', header: 'clean', desc: 'Designed with clean, compact spacing, allowing entry-level applicants to turn projects into statements', isPremium: false },
  { id: 'tpl-210', name: 'The Pitch Deck Style', category: 'Creative', layout: 'magazine', theme: 'purple', font: 'modern', header: 'clean', desc: 'Uses modern typographic hierarchies to make your personal history read like a startup pitch', isPremium: false },

  // --- ATS-OPTIMIZED HYBRID (tpl-211 to tpl-220) ---
  { id: 'tpl-211', name: 'The Single-Stream Perfect', category: 'Minimal', layout: 'classic', theme: 'slate', font: 'modern', header: 'clean', desc: 'A purely single-column document flowing top-to-bottom, eliminating multi-column parsing errors', isPremium: false },
  { id: 'tpl-212', name: 'The Standard Tables', category: 'Classic', layout: 'classic', theme: 'navy', font: 'modern', header: 'border', desc: 'Built using clean, borderless grids to ensure text blocks never overlap or confuse parsers', isPremium: false },
  { id: 'tpl-213', name: 'The Keyword Master', category: 'Executive', layout: 'classic', theme: 'navy', font: 'modern', header: 'clean', desc: 'Includes a spacious Skills Matrix block at the top, allowing easy integration of job keywords', isPremium: false },
  { id: 'tpl-214', name: 'The Universal Safe', category: 'Minimal', layout: 'classic', theme: 'slate', font: 'modern', header: 'clean', desc: 'Uses standard clean fonts paired with standard section headings to maximize ATS parsing accuracy', isPremium: false },
  { id: 'tpl-215', name: 'The Bullet Matrix', category: 'Classic', layout: 'classic', theme: 'charcoal', font: 'modern', header: 'border', desc: 'Organizes bullet points into highly structured task-action-result formats with explicit spacing', isPremium: false },
  { id: 'tpl-216', name: 'The Iconless Clean', category: 'Minimal', layout: 'classic', theme: 'slate', font: 'modern', header: 'clean', desc: 'Bypasses all SVG graphics and symbols, removing parsing elements that confuse corporate ATS', isPremium: false },
  { id: 'tpl-217', name: 'The Straight Header', category: 'Minimal', layout: 'classic', theme: 'charcoal', font: 'modern', header: 'clean', desc: 'Places contact info on single horizontal lines rather than floating grids for address parsers', isPremium: false },
  { id: 'tpl-218', name: 'The Direct Date', category: 'Classic', layout: 'classic', theme: 'slate', font: 'modern', header: 'border', desc: 'Aligns dates directly alongside company names to ensure sorting algorithms map histories accurately', isPremium: false },
  { id: 'tpl-219', name: 'The No-Background Minimal', category: 'Minimal', layout: 'classic', theme: 'slate', font: 'modern', header: 'clean', desc: 'Uses an entirely white background layout to ensure text contrast remains high under automated parsers', isPremium: false },
  { id: 'tpl-220', name: 'The Clean Text Anchor', category: 'Minimal', layout: 'classic', theme: 'slate', font: 'modern', header: 'clean', desc: 'A pristine, foundational template combining premium layout design with 100% text-selectable data', isPremium: false }
];

// Theme accent colors — used for section titles, dividers, skill tags
export const themeHexMap = {
  slate: '#475569',
  emerald: '#059669',
  navy: '#1e3a8a',
  amber: '#d97706',
  purple: '#7c3aed',
  coral: '#f43f5e',
  olive: '#84cc16',
  rose: '#db2777',
  chocolate: '#8d5b4c',
  teal: '#0d9488',
  crimson: '#e11d48',
  charcoal: '#374151',
  indigo: '#4f46e5',
  gold: '#d97706',
  mint: '#10b981',
  lavender: '#8b5cf6',
  sky: '#0284c7',
  // Premium dark themes — accent color for headings, dividers, skill tags
  midnight: '#4a90d9',
  onyx: '#a0aec0',
  plum: '#c084fc',
  ocean: '#38bdf8',
  graphite: '#94a3b8',
  wine: '#f9a8d4',
  forest: '#6ee7b7',
  steel: '#7dd3fc'
};

// Light accent backgrounds for skill tags on white areas
export const themeLightHexMap = {
  slate: '#f1f5f9',
  emerald: '#ecfdf5',
  navy: '#eff6ff',
  amber: '#fffbeb',
  purple: '#f5f3ff',
  coral: '#fff1f2',
  olive: '#f7fee7',
  rose: '#fdf2f8',
  chocolate: '#efebe9',
  teal: '#f0fdfa',
  crimson: '#fff1f2',
  charcoal: '#f8fafc',
  indigo: '#e0e7ff',
  gold: '#fffbeb',
  mint: '#ecfdf5',
  lavender: '#f5f3ff',
  sky: '#f0f9ff',
  midnight: '#e0f2fe',
  onyx: '#f1f5f9',
  plum: '#f3e8ff',
  ocean: '#e0f2fe',
  graphite: '#f1f5f9',
  wine: '#fce7f3',
  forest: '#ecfdf5',
  steel: '#e0f2fe'
};

// Dark sidebar background colors for premium dark-* and bold-header layouts
export const themeDarkBgMap = {
  midnight: '#1a1a3e',
  onyx: '#1c1c1e',
  plum: '#3b1f54',
  ocean: '#0a2647',
  graphite: '#2d3436',
  wine: '#5c1a1b',
  forest: '#1a3c34',
  steel: '#2c3e6b'
};
